version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-service
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
    networks:
      - phishforge_network

networks:
  phishforge_network:
    name: phishforge_network
    driver: bridge
